/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Genetico.Configuracion;
import Genetico.GeneticoDistribuidoImagenes;
import Genetico.Individuo;
import HerramientasGenetico.Cruza.TipoCruza;
import HerramientasGenetico.Seleccion.TipoSeleccion;
import HerramientasImagenes.Almacenamiento;
import HerramientasImagenes.Conversion;
import HerramientasImagenes.Conversion.CanalColor;
import HerramientasImagenes.JFrameImagen;
import io.ImageManager;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import Conexiones.Enviar;
import Conexiones.RecibirIguales;
import Conexiones.RecibirMaestro;
import java.io.IOException;
/**
 *
 * Nombres: Miguel Angel Cervantes Garcia, Juan Antonio Ovalle Patiño
 * Matriculas: 2017670201, 2017670891
 * Tema del programa: Algortimo Genetico Distribuido
 * Descripcion: Es un algorutmo genetico que trata de recrear la imagen que se escogio, y diferentes computadoras
 *              van a resolver un cal¿nal en especial y al final se manda al maestro para crear la imagen resultante.
 * Fecha: 3 / Junio / 2019
 * Programa Academico: Ingenieria en Sistemas Computacionales
 * Aprendizaje: Aplicaciones para Comunicaciones de Red & Algoritmos Geneticos
 * 
 */
public class Secundario extends javax.swing.JFrame {
    
    private Configuracion configuracion;
    private GeneticoDistribuidoImagenes genetico;
    private Image imagen;
    private CanalColor canalColor;
    private RecibirMaestro receptor;
    private RecibirIguales recibirIguales;
    /**
     * Creates new form Secundario
     * @param canalColor
     * @param porto
     */
    public Secundario(CanalColor canalColor, int porto) {
        initComponents();
        this.jLabel8.setText(porto+"");
        this.historial.setEditable(false);
        this.imagen= null;
        this.genetico=null;
        this.canalColor= canalColor;
        switch(canalColor){
            case ROJO:
                this.canal.setText("Rojo");
                break;
            case VERDE:
                this.canal.setText("Verde");
                break;
            case AZUL:
                this.canal.setText("Azul");
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generaciones = new javax.swing.JTextField();
        sizeP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        canal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        muta = new javax.swing.JTextField();
        cruza = new javax.swing.JComboBox<>();
        seleccionPadre = new javax.swing.JComboBox<>();
        mejorG = new javax.swing.JLabel();
        individuoInicial = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        historial = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        ip = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        seleccionMadre = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        nombre = new javax.swing.JTextField();
        port = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numero de Generaciones");

        canal.setText("Canal Color");

        jLabel3.setText("Numero de Indivduos");

        jLabel4.setText("Probabilidad de muta");

        jLabel5.setText("Tipo de Cruza");

        jLabel6.setText("Tipo de Seleccion");

        cruza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pixel", "Fila", "Columna", "Aleatorio" }));

        seleccionPadre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Torneo", "Aleatorio", "Ruleta" }));

        historial.setEditable(false);
        historial.setColumns(20);
        historial.setLineWrap(true);
        historial.setRows(5);
        historial.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        historial.setDragEnabled(true);
        historial.setSelectedTextColor(new java.awt.Color(255, 0, 0));
        historial.setSelectionColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(historial);

        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("IP:");

        jButton4.setText("Cargar Individuo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("Abrir Imagen");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Fila");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Columna");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Pixel");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel2.setText("Cambiar mascara de Cruza");

        seleccionMadre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Torneo", "Aleatorio", "Ruleta" }));

        jButton8.setText("Enviar Mejor");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Guardar Individuo");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel7.setText("Puerto;");

        jLabel8.setText("Port");

        jLabel10.setText("Puerto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seleccionPadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seleccionMadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cruza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel8))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sizeP)
                                    .addComponent(generaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(muta)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(individuoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(canal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mejorG, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(127, 127, 127))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ip, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jButton8)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombre)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(canal)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(generaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sizeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(muta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cruza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(seleccionPadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seleccionMadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6)
                            .addComponent(jButton7))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(individuoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mejorG, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jButton8)
                        .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton9))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(this.imagen!=null){
            if(this.jButton1.getText().equals("Iniciar")){//Si aun no esta en ejecucion el genetico
                try{
                    long gen = Integer.parseInt(this.generaciones.getText());
                    int indi= Integer.parseInt(this.sizeP.getText());
                    double muta= Double.parseDouble(this.muta.getText());
                    this.jButton1.setText("Modificar");
                    TipoCruza tp;
                    switch (this.cruza.getSelectedIndex()) {
                        case 0:
                            tp= TipoCruza.CRUZA_PIXEL;
                            break;
                        case 1:
                            tp= TipoCruza.CRUZA_FILA;
                            break;
                        case 2:
                            tp= TipoCruza.CRUZA_COLUMNA;
                            break;
                        case 3:
                            tp= TipoCruza.CRUZA_ALEATORIA;
                            break;
                        default:
                            tp= TipoCruza.CRUZA_ALEATORIA;
                            break;
                    }
                    TipoSeleccion[] tipoS= new TipoSeleccion[2];
                    switch(this.seleccionPadre.getSelectedIndex()){
                        case 0:
                            tipoS[0]=TipoSeleccion.TORNEO;
                            break;
                        case 1:
                            tipoS[0]=TipoSeleccion.RANDOM;
                            break;
                        case 2:
                            tipoS[0]=TipoSeleccion.RULETA;
                            break;
                        default:
                            break;
                    }
                    
                    switch(this.seleccionMadre.getSelectedIndex()){
                        case 0:
                            tipoS[1]=TipoSeleccion.TORNEO;
                            break;
                        case 1:
                            tipoS[1]=TipoSeleccion.RANDOM;
                            break;
                        case 2:
                            tipoS[1]=TipoSeleccion.RULETA;
                            break;
                        default:
                            break;
                    }
                    this.configuracion= new Configuracion(gen, indi, muta, tipoS, tp, this.canalColor);
                    this.genetico= new GeneticoDistribuidoImagenes(configuracion, this.historial, this.mejorG);
                    this.individuoInicial.setIcon(new  ImageIcon(Conversion.matrizAImagenParcial(this.genetico.getPoblacion().getMejor().getGenotipo(), this.configuracion.getCanalColor()).getScaledInstance(200, 200, BufferedImage.TYPE_INT_RGB)));
                    this.genetico.start();
                    try{
                        this.recibirIguales= new RecibirIguales(this.genetico,Integer.parseInt(this.jLabel8.getText()));
                        this.recibirIguales.start();
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null,"Introduzca el puerto de manera adecuada");
                    }
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null,"Introduzca los datos de manera adecuada");
                }
            }else{
                try{
                    int gen = Integer.parseInt(this.generaciones.getText());
                    int indi= Integer.parseInt(this.sizeP.getText());
                    double muta= Double.parseDouble(this.muta.getText());
                    TipoCruza tp=TipoCruza.CRUZA_PIXEL;
                    switch (this.cruza.getSelectedIndex()) {
                        case 0:
                            tp= TipoCruza.CRUZA_PIXEL;
                            break;
                        case 1:
                            tp= TipoCruza.CRUZA_FILA;
                            break;
                        case 2:
                            tp= TipoCruza.CRUZA_COLUMNA;
                            break;
                        case 3:
                            tp= TipoCruza.CRUZA_ALEATORIA;
                            break;
                        default:
                            break;
                    }
                    TipoSeleccion[] tipoS= new TipoSeleccion[2];
                    switch(this.seleccionPadre.getSelectedIndex()){
                        case 0:
                            tipoS[0]=TipoSeleccion.TORNEO;
                            break;
                        case 1:
                            tipoS[0]=TipoSeleccion.RANDOM;
                            break;
                        case 2:
                            tipoS[0]=TipoSeleccion.RULETA;
                            break;
                        default:
                            break;
                    }
                    
                    switch(this.seleccionMadre.getSelectedIndex()){
                        case 0:
                            tipoS[1]=TipoSeleccion.TORNEO;
                            break;
                        case 1:
                            tipoS[1]=TipoSeleccion.RANDOM;
                            break;
                        case 2:
                            tipoS[1]=TipoSeleccion.RULETA;
                            break;
                        default:
                            break;
                    }
                    //Aqui se modifican todos los parametros
                    this.configuracion.setNumGeneraciones(gen);
                    this.configuracion.setTamPoblaciobn(indi);
                    this.configuracion.setProbabilidadMuta(muta);
                    this.configuracion.setTipoCruza(tp);
                    this.configuracion.setTipoSeleccion(tipoS);
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null,"Introduzca los datos de manera adecuada");
                }
            }
        }else{
            JOptionPane.showMessageDialog(null,"Abra una imagen primero");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(this.imagen!=null && (this.genetico!=null)){
            Image individuo = ImageManager.openImage();
            try{
                Individuo cargado= new Individuo(Conversion.imagenAGenotipo(individuo, this.canalColor), this.canalColor);
                System.out.println(cargado.getFitness());
                this.genetico.getPoblacion().addIndividuo(cargado);
            }catch(Exception e){
                
            }
        }else JOptionPane.showMessageDialog(null,"Abra una imagen primero");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            this.imagen=ImageManager.openImage();
            Conversion.imagenAMatriz(imagen);
            new JFrameImagen(this.imagen);
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(!this.nombre.getText().isEmpty()){
            int imate[][]= this.genetico.getDefinitivo().getGenotipo();
            Almacenamiento.guardadIndividuo(Conversion.matrizAImagenCompleta(imate,imate,imate), this.nombre.getText());
        }else JOptionPane.showMessageDialog(null,"Escriba un nombre");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(this.genetico!=null)
            this.configuracion.changeMascaraPixeles();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(this.genetico!=null)
        this.configuracion.changeMascaraColumnas();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(this.genetico!=null)
        this.configuracion.changeMascaraFilas();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(this.genetico!=null)
        try {
            Enviar.enviarIndididuo(this.ip.getText(), Integer.parseInt(this.port.getText()), this.genetico.getDefinitivo());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Inicie el genetico");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Secundario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Secundario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Secundario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Secundario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Secundario(CanalColor.ROJO, 12345).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel canal;
    private javax.swing.JComboBox<String> cruza;
    private javax.swing.JTextField generaciones;
    private javax.swing.JTextArea historial;
    private javax.swing.JLabel individuoInicial;
    private javax.swing.JTextField ip;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mejorG;
    private javax.swing.JTextField muta;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField port;
    private javax.swing.JComboBox<String> seleccionMadre;
    private javax.swing.JComboBox<String> seleccionPadre;
    private javax.swing.JTextField sizeP;
    // End of variables declaration//GEN-END:variables
}
