/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Genetico.Configuracion;
import Genetico.GeneticoDistribuidoImagenes;
import Genetico.Individuo;
import HerramientasGenetico.Cruza.TipoCruza;
import HerramientasGenetico.Seleccion.TipoSeleccion;
import HerramientasImagenes.Almacenamiento;
import HerramientasImagenes.Conversion;
import HerramientasImagenes.Conversion.CanalColor;
import io.ImageManager;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import Conexiones.Enviar;
import Conexiones.RecibirIguales;
import Conexiones.RecibirMaestro;
import java.awt.Toolkit;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.text.DefaultCaret;
/**
 *
 * Nombres: Miguel Angel Cervantes Garcia, Juan Antonio Ovalle Patiño
 * Matriculas: 2017670201, 2017670891
 * Tema del programa: Algortimo Genetico Distribuido
 * Descripcion: Es un algorutmo genetico que trata de recrear la imagen que se escogio, y diferentes computadoras
 *              van a resolver un cal¿nal en especial y al final se manda al maestro para crear la imagen resultante.
 * Fecha: 3 / Junio / 2019
 * Programa Academico: Ingenieria en Sistemas Computacionales
 * Aprendizaje: Aplicaciones para Comunicaciones de Red & Algoritmos Geneticos
 * 
 */
public class Secundario extends javax.swing.JFrame {
    
    private Configuracion configuracion;
    private GeneticoDistribuidoImagenes genetico;
    private Image imagen;
    private Icon start;
    private CanalColor canalColor;
    private RecibirMaestro receptor;
    private RecibirIguales recibirIguales;
    /**
     * Creates new form Secundario
     * @param canalColor
     * @param porto
     */
    public Secundario(CanalColor canalColor, int porto, Image img) {
        setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        this.jLabel8.setText(porto+"");
        this.historial.setEditable(false);
        this.imagen= img;
        this.genetico=null;
        this.canalColor= canalColor;
        switch(canalColor){
            case ROJO:
                this.canal.setText("Rojo");
                break;
            case VERDE:
                this.canal.setText("Verde");
                break;
            case AZUL:
                this.canal.setText("Azul");
                break;
        }
        DefaultCaret caret = (DefaultCaret)historial.getCaret();
        caret.setUpdatePolicy(DefaultCaret.OUT_BOTTOM);
        
        Image icon = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagen/fondo2.png"));
        Icon fond = new ImageIcon(icon.getScaledInstance(fondo.getWidth(), fondo.getHeight()+8, Image.SCALE_DEFAULT));
        fondo.setIcon(fond);
        
        icon = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagen/barra.png"));
        Icon ba = new ImageIcon(icon.getScaledInstance(barra.getWidth(), barra.getHeight(), Image.SCALE_DEFAULT));
        mover mml = new mover(barra);
        barra.addMouseListener(mml);
        barra.addMouseMotionListener(mml);
        barra.setIcon(ba);
        barra.setOpaque(true);
        barra.setSize(780, 20);
        
        icon = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagen/close.png"));
        Icon clos = new ImageIcon(icon.getScaledInstance(this.close.getWidth(), this.close.getHeight(), Image.SCALE_DEFAULT));
        close.setIcon(clos);
        
        icon = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagen/play2.jpg"));
        start = new ImageIcon(icon.getScaledInstance(jButton1.getWidth(), jButton1.getHeight(), Image.SCALE_DEFAULT));
        jButton1.setIcon(start);
        
        icon = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagen/cargar2.png"));
        Icon cargar = new ImageIcon(icon.getScaledInstance(jButton4.getWidth(), jButton4.getHeight(), Image.SCALE_DEFAULT));
        jButton4.setIcon(cargar);
        
        icon = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagen/enviar2.jpg"));
        Icon enviar = new ImageIcon(icon.getScaledInstance(jButton8.getWidth(), jButton8.getHeight(), Image.SCALE_DEFAULT));
        jButton8.setIcon(enviar);
        
        icon = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagen/guardar2.png"));
        Icon guardar = new ImageIcon(icon.getScaledInstance(jButton9.getWidth(), jButton9.getHeight(), Image.SCALE_DEFAULT));
        jButton9.setIcon(guardar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generaciones = new javax.swing.JTextField();
        sizeP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        canal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        muta = new javax.swing.JTextField();
        cruza = new javax.swing.JComboBox<>();
        seleccionPadre = new javax.swing.JComboBox<>();
        mejorG = new javax.swing.JLabel();
        individuoInicial = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        historial = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        ip = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        seleccionMadre = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        close = new javax.swing.JButton();
        nombre = new javax.swing.JTextField();
        port = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        barra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(generaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 111, -1));
        getContentPane().add(sizeP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 111, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Numero de Generaciones");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, 20));

        canal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        canal.setForeground(new java.awt.Color(255, 255, 255));
        canal.setText("Canal Color");
        getContentPane().add(canal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Numero de Indivduos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 120, 20));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Probabilidad de muta");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 120, 20));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo de Cruza");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 120, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tipo de Seleccion");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 120, 50));
        getContentPane().add(muta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 111, -1));

        cruza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pixel", "Fila", "Columna", "Aleatorio" }));
        getContentPane().add(cruza, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 110, -1));

        seleccionPadre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Torneo", "Aleatorio", "Ruleta" }));
        getContentPane().add(seleccionPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 110, -1));
        getContentPane().add(mejorG, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 200, 200));
        getContentPane().add(individuoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 200));

        historial.setEditable(false);
        historial.setBackground(new java.awt.Color(0, 0, 0));
        historial.setColumns(20);
        historial.setForeground(new java.awt.Color(204, 204, 204));
        historial.setLineWrap(true);
        historial.setRows(5);
        historial.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        historial.setDragEnabled(true);
        historial.setSelectedTextColor(new java.awt.Color(255, 0, 0));
        historial.setSelectionColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(historial);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 224, 206));

        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 80, 80));
        getContentPane().add(ip, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 113, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("IP:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, 30));

        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 80, 80));

        jButton5.setBackground(new java.awt.Color(0, 0, 255));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Fila");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 55, -1));

        jButton6.setBackground(new java.awt.Color(0, 255, 0));
        jButton6.setText("Columna");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, -1));

        jButton7.setBackground(new java.awt.Color(255, 0, 0));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Pixel");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cambiar mascara de Cruza");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, 30));

        seleccionMadre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Torneo", "Aleatorio", "Ruleta" }));
        getContentPane().add(seleccionMadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 110, -1));

        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 80, 80));

        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 80, 80));

        close.setContentAreaFilled(false);
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 30, 30));
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 119, -1));
        getContentPane().add(port, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 76, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Puerto");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Port");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Puerto:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 820, 470));

        barra.setBackground(new java.awt.Color(255, 255, 255));
        barra.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(this.imagen!=null){
            //if(this.jButton1.getText().equals("Iniciar")){//Si aun no esta en ejecucion el genetico
            if(this.jButton1.getIcon().equals(start)){
                try{
                    long gen = Integer.parseInt(this.generaciones.getText());
                    int indi= Integer.parseInt(this.sizeP.getText());
                    double muta= Double.parseDouble(this.muta.getText());
//                    this.jButton1.setText("Modificar");
                    Image icon = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagen/editar.jpg"));
                    Icon mod = new ImageIcon(icon.getScaledInstance(jButton1.getWidth(), jButton1.getHeight(), Image.SCALE_DEFAULT));
                    jButton1.setIcon(mod);
                    TipoCruza tp;
                    switch (this.cruza.getSelectedIndex()) {
                        case 0:
                            tp= TipoCruza.CRUZA_PIXEL;
                            break;
                        case 1:
                            tp= TipoCruza.CRUZA_FILA;
                            break;
                        case 2:
                            tp= TipoCruza.CRUZA_COLUMNA;
                            break;
                        case 3:
                            tp= TipoCruza.CRUZA_ALEATORIA;
                            break;
                        default:
                            tp= TipoCruza.CRUZA_ALEATORIA;
                            break;
                    }
                    TipoSeleccion[] tipoS= new TipoSeleccion[2];
                    switch(this.seleccionPadre.getSelectedIndex()){
                        case 0:
                            tipoS[0]=TipoSeleccion.TORNEO;
                            break;
                        case 1:
                            tipoS[0]=TipoSeleccion.RANDOM;
                            break;
                        case 2:
                            tipoS[0]=TipoSeleccion.RULETA;
                            break;
                        default:
                            break;
                    }
                    
                    switch(this.seleccionMadre.getSelectedIndex()){
                        case 0:
                            tipoS[1]=TipoSeleccion.TORNEO;
                            break;
                        case 1:
                            tipoS[1]=TipoSeleccion.RANDOM;
                            break;
                        case 2:
                            tipoS[1]=TipoSeleccion.RULETA;
                            break;
                        default:
                            break;
                    }
                    this.configuracion= new Configuracion(gen, indi, muta, tipoS, tp, this.canalColor);
                    this.genetico= new GeneticoDistribuidoImagenes(configuracion, this.historial, this.mejorG);
                    this.individuoInicial.setIcon(new  ImageIcon(Conversion.matrizAImagenParcial(this.genetico.getPoblacion().getMejor().getGenotipo(), this.configuracion.getCanalColor()).getScaledInstance(200, 200, BufferedImage.TYPE_INT_RGB)));
                    this.genetico.start();
                    try{
                        this.recibirIguales= new RecibirIguales(this.genetico, this.configuracion,Integer.parseInt(this.jLabel8.getText()));
                        this.recibirIguales.start();
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null,"Introduzca el puerto de manera adecuada");
                    }
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null,"Introduzca los datos de manera adecuada");
                }
            }else{
                try{
                    int gen = Integer.parseInt(this.generaciones.getText());
                    int indi= Integer.parseInt(this.sizeP.getText());
                    double muta= Double.parseDouble(this.muta.getText());
                    TipoCruza tp=TipoCruza.CRUZA_PIXEL;
                    switch (this.cruza.getSelectedIndex()) {
                        case 0:
                            tp= TipoCruza.CRUZA_PIXEL;
                            break;
                        case 1:
                            tp= TipoCruza.CRUZA_FILA;
                            break;
                        case 2:
                            tp= TipoCruza.CRUZA_COLUMNA;
                            break;
                        case 3:
                            tp= TipoCruza.CRUZA_ALEATORIA;
                            break;
                        default:
                            break;
                    }
                    TipoSeleccion[] tipoS= new TipoSeleccion[2];
                    switch(this.seleccionPadre.getSelectedIndex()){
                        case 0:
                            tipoS[0]=TipoSeleccion.TORNEO;
                            break;
                        case 1:
                            tipoS[0]=TipoSeleccion.RANDOM;
                            break;
                        case 2:
                            tipoS[0]=TipoSeleccion.RULETA;
                            break;
                        default:
                            break;
                    }
                    
                    switch(this.seleccionMadre.getSelectedIndex()){
                        case 0:
                            tipoS[1]=TipoSeleccion.TORNEO;
                            break;
                        case 1:
                            tipoS[1]=TipoSeleccion.RANDOM;
                            break;
                        case 2:
                            tipoS[1]=TipoSeleccion.RULETA;
                            break;
                        default:
                            break;
                    }
                    //Aqui se modifican todos los parametros
                    this.configuracion.setNumGeneraciones(gen);
                    this.configuracion.setTamPoblaciobn(indi);
                    this.configuracion.setProbabilidadMuta(muta);
                    this.configuracion.setTipoCruza(tp);
                    this.configuracion.setTipoSeleccion(tipoS);
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null,"Introduzca los datos de manera adecuada");
                }
            }
        }else{
            JOptionPane.showMessageDialog(null,"Abra una imagen primero");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(this.imagen!=null && (this.genetico!=null)){
            Image individuo = ImageManager.openImage();
            try{
                Individuo cargado= new Individuo(Conversion.imagenAGenotipo(individuo, this.canalColor), this.canalColor);
                System.out.println(cargado.getFitness());
                this.genetico.getPoblacion().addIndividuo(cargado);
            }catch(Exception e){
                
            }
        }else JOptionPane.showMessageDialog(null,"Abra una imagen primero");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(!this.nombre.getText().isEmpty()){
            int imate[][]= this.genetico.getDefinitivo().getGenotipo();
            Almacenamiento.guardadIndividuo(Conversion.matrizAImagenCompleta(imate,imate,imate), this.nombre.getText());
        }else JOptionPane.showMessageDialog(null,"Escriba un nombre");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(this.genetico!=null)
            this.configuracion.changeMascaraPixeles();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(this.genetico!=null)
        this.configuracion.changeMascaraColumnas();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(this.genetico!=null)
        this.configuracion.changeMascaraFilas();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(this.genetico!=null)
        try {
            Enviar.enviarIndididuo(this.ip.getText(), Integer.parseInt(this.port.getText()), this.genetico.getDefinitivo());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Inicie el genetico");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        //CLOSE
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Secundario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Secundario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Secundario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Secundario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Secundario(CanalColor.ROJO, 12345, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barra;
    private javax.swing.JLabel canal;
    private javax.swing.JButton close;
    private javax.swing.JComboBox<String> cruza;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField generaciones;
    private javax.swing.JTextArea historial;
    private javax.swing.JLabel individuoInicial;
    private javax.swing.JTextField ip;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mejorG;
    private javax.swing.JTextField muta;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField port;
    private javax.swing.JComboBox<String> seleccionMadre;
    private javax.swing.JComboBox<String> seleccionPadre;
    private javax.swing.JTextField sizeP;
    // End of variables declaration//GEN-END:variables
}
